#!/usr/bin/env bash
echo "== create vpc"

set -e

REGION="us-east-2"

echo "executing create vpc..."

# create vpc
VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--tag-specifications "ResourceType=vpc,Tags=[{Key=Name, Value=my-vpc}]" \
--region $REGION \
--query Vpc.VpcId \
--output text)

echo "vpc create complete!"

echo "VPC_ID: $VPC_ID"

# turn on DNS hostnames

echo "modifying vpc to enable DNS hostnames..."

aws ec2 modify-vpc-attribute \
--vpc-id $VPC_ID \
--enable-dns-hostnames "{\"Value\":true}" \
--region $REGION

echo "enabled DNS hostnames!"

# create internet gateway

echo "creating internet gateway for VPC: $VPC_ID ..."

IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--region $REGION \
--output text)

echo "IGW_ID: $IGW_ID"

echo "successfully created internet gateway!"

# attach internet gateway

echo "attaching internet gateway: $IGW_ID to VPC: $VPC_ID ..."

aws ec2 attach-internet-gateway \
--internet-gateway-id $IGW_ID \
--region $REGION \
--vpc-id $VPC_ID

echo "successfully attached internet gateway to vpc!"

# create a new subnet

echo "creating a new subnet for VPC..."

SUBNET_ID=$(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--cidr-block "172.1.0.0/20" \
--region $REGION \
--query Subnet.SubnetId \
--output text)

echo "SUBNET_ID: $SUBNET_ID"

echo "successfully created subnet!"

# auto assign IPv4 addresses

echo "auto assigning IPv4 addresses to subnet..."

aws ec2 modify-subnet-attribute \
--subnet-id $SUBNET_ID \
--region $REGION \
--map-public-ip-on-launch

echo "successfully auto assigned IPv4 addresses!"

# explicitly associate a subnet

echo "querying route table id..."

RT_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--region $REGION \
--query "RouteTables[].RouteTableId[]" \
--output text)

echo "RT_ID: $RT_ID"

echo "successfully queried route table id!"

echo "explicitly associating subnet with VPC: $VPC_ID ..."

ASSOC_ID=$(aws ec2 associate-route-table \
--route-table-id $RT_ID \
--region $REGION \
--subnet-id $SUBNET_ID \
--query AssociationId \
--output text
)
echo "successfully associated route table: $RT_ID with subnet: $SUBNET_ID!"

# add a route for route table to internet gateway

echo "adding route for route table..."

aws ec2 create-route \
--route-table-id $RT_ID \
--destination-cidr-block "0.0.0.0/0" \
--region $REGION \
--gateway-id $IGW_ID

echo "added route to route table: $RT_ID to internet gateway: $IGW_ID!"

echo "------------VPC CREATION COMPLETE------------"

# print out delete command
echo "./delete-vpc $VPC_ID $IGW_ID $SUBNET_ID"