#!/usr/bin/env bash
echo "== delete vpc"

set -e

# check if thh argument is not provided
if [ -z "$1" ]; then
    echo "Argument not provided."
else
    export VPC_ID="$1"
fi

# delete vpc
aws ec2 delete-vpc --vpc-id $VPC_ID

# detach IGW

# delete the IGW

# delete vpc

